jdk: oraclejdk8

install:
  # Download and unzip the Android SDK tools (if not already there thanks to the cache mechanism)
  - if test ! -e $HOME/android-sdk-download/sdk-tools-linux-3859397.zip ; then curl https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip > $HOME/android-sdk-download/sdk-tools-linux-3859397.zip ; fi
  - unzip -n $HOME/android-sdk-download/sdk-tools-linux-3859397.zip -d $HOME/android-sdk
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager --update