language: android
jdk: oraclejdk8

before_cache:
  # Do not cache a few Gradle files/directories (see https://docs.travis-ci.com/user/languages/java/#Caching)
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    # Android SDK
    - $HOME/android-sdk-download
    - $HOME/android-sdk

    # Gradle dependencies
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

    # Android build cache (see http://tools.android.com/tech-docs/build-cache)
    - $HOME/.android/build-cache

install:
  # Download and unzip the Android SDK tools (if not already there thanks to the cache mechanism)
  - if test ! -e $HOME/android-sdk-download/sdk-tools-linux-3859397.zip ; then curl https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip > $HOME/android-sdk-download/sdk-tools-linux-3859397.zip ; fi
  - unzip -n $HOME/android-sdk-download/sdk-tools-linux-3859397.zip -d $HOME/android-sdk

  # Install or update Android SDK components (will not do anything if already up to date thanks to the cache mechanism)
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'tools'
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'platform-tools'
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'build-tools;26.0.0'
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'platforms;android-26'
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'extras;android;m2repository'
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'extras;google;google_play_services'
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'extras;google;m2repository'

env:
  - ANDROID_HOME=$HOME/android-sdk

script: ./gradlew test