android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-26.0.0
    - android-26

env:
  - ANDROID_HOME=/usr/local/android-sdk-24.0.2

before_install:
 - chmod +x gradlew
 - ls /usr/local

script: ./gradlew test